// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToggleAvailability.Server.Data;

#nullable disable

namespace ToggleAvailability.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831155415_AddOfficeHistory")]
    partial class AddOfficeHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("ToggleAvailability.Server.Models.OfficeHistory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeInOffice")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Date");

                    b.ToTable("OfficeHistories");
                });

            modelBuilder.Entity("ToggleAvailability.Server.Models.OfficeHistoryOutOfOffice", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Date", "Status");

                    b.ToTable("OfficeHistoryOutOfOffice");
                });

            modelBuilder.Entity("ToggleAvailability.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InOfficeStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OutOfOfficeStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
